<?php

require_once 'db/Users.php';

// Contains any error messages generated by handleLogin
class LoginFormData
{
    public $error = null;
}

// a handler for the login form
class LoginFormHandler
{
    // constructor instantiates a DBUsers
    public function __construct()
    {
        $this->dbUsers = new DBUsers();
    }

    /*
    A handler for the login form.

    If a POSTED username and password combination can be verified using the
    DBUsers' verifyUser method, then create a 'username' session and redirect
    to index.php. If such a session already exists, redirect there too.
     */
    public function handleLogin()
    {
        $data = new LoginFormData();
        $data->error = null;

        if (!isset($_SESSION['username'])) {
            // See if a login form was submitted with a username for login
            if (isset($_POST['username']) && isset($_POST['password'])) {
                // get the username
                $username = htmlentities(trim($_POST['username']));
                // get the password
                $password = htmlentities(trim($_POST['password']));
                // if username or password is missing
                if (!$username || !$password) {
                    $error = "You need to fill in both the username and password.";
                }
                // verify user
                $userverified = $this->dbUsers->verifyUser($username, $password);
                // if username and password are valid, login
                if ($userverified) {
                    $_SESSION['username'] = $username;
                    header("Location: index.php");
                    exit();
                    //if username and login are not valid, display error message
                } else {
                    $data->error = "You need a valid username and password.";
                }
            }
        } else {
            header("Location: index.php");
            exit();
        }

        return $data;
    }

}
